spring:
  cloud:
    aws:
      region:
        static: ${AWS_DEFAULT_REGION}
  rabbitmq:
    listener:
      type: simple
      simple:
        auto-startup: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    env:
      enabled: false
    configprops:
      show-values: never
    beans:
      show-values: never
    health:
      show-details: never
  health:
    circuitbreakers:
      enabled: true
    redis:
      enabled: true
