apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamodb-data
  labels:
    app: dynamodb-local
    component: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
