apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __DB_DEPLOY__-data
  labels:
    app: __DB_DEPLOY__
    component: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
