apiVersion: v1
kind: Service
metadata:
  name: __DB_SVC__
  labels:
    app: __DB_DEPLOY__
    component: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: __DB_DEPLOY__
