apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: __REDIS_DEPLOY__-data
  labels:
    app: __REDIS_DEPLOY__
    component: cache
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
