apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hermes-dev

resources:
  - gateway-secrets-vault.yaml
  - user-service-secrets-vault.yaml
  - auth-postgres-secrets-vault.yaml
  - user-postgres-secrets-vault.yaml
  - rabbitmq-secrets-vault.yaml
  - keycloak-secrets-vault.yaml
  - auth-service-secrets-vault.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: hermes
      environment: dev
      secret-source: vault
