apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-hermes-dev
    kind: ClusterSecretStore
  target:
    name: rabbitmq-secrets
    creationPolicy: Owner
  data:
    - secretKey: RABBITMQ_DEFAULT_USER
      remoteRef:
        key: hermes/dev/shared/rabbitmq
        property: username
    - secretKey: RABBITMQ_DEFAULT_PASS
      remoteRef:
        key: hermes/dev/shared/rabbitmq
        property: password
    - secretKey: RABBITMQ_USERNAME
      remoteRef:
        key: hermes/dev/shared/rabbitmq
        property: username
    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: hermes/dev/shared/rabbitmq
        property: password
