apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: user-service-secrets-vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-hermes-dev
    kind: ClusterSecretStore
  target:
    name: user-service-secrets-vault
    creationPolicy: Owner
  data:
    - secretKey: GATEWAY_SECRET
      remoteRef:
        key: hermes/dev/shared/jwt-signing-key
        property: value
    - secretKey: APP_USER
      remoteRef:
        key: hermes/dev/services/user-db/postgres
        property: APP_USER
    - secretKey: APP_PASSWORD
      remoteRef:
        key: hermes/dev/services/user-db/postgres
        property: APP_PASSWORD
    - secretKey: FLYWAY_USER
      remoteRef:
        key: hermes/dev/services/user-db/postgres
        property: FLYWAY_USER
    - secretKey: FLYWAY_PASSWORD
      remoteRef:
        key: hermes/dev/services/user-db/postgres
        property: FLYWAY_PASSWORD
    - secretKey: RABBITMQ_USERNAME
      remoteRef:
        key: hermes/dev/shared/rabbitmq
        property: username
    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: hermes/dev/shared/rabbitmq
        property: password
