apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-hermes-staging
    kind: ClusterSecretStore
  target:
    name: keycloak-secrets
    creationPolicy: Owner
  data:
    - secretKey: KEYCLOAK_ADMIN
      remoteRef:
        key: hermes/staging/services/keycloak/keycloak-admin
        property: username
    - secretKey: KEYCLOAK_ADMIN_PASSWORD
      remoteRef:
        key: hermes/staging/services/keycloak/keycloak-admin
        property: password
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: hermes/staging/shared/github-oauth
        property: client_secret
