apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hermes-staging

resources:
  - ../../../../clusters/staging/namespace.yaml
  - gateway-secrets.yaml
  - user-service-secrets.yaml
  - auth-postgres-secrets.yaml
  - user-postgres-secrets.yaml
  - rabbitmq-secrets.yaml
  - keycloak-secrets.yaml
  - auth-service-secrets.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: hermes
      environment: staging
      secret-source: aws-secrets-manager
