apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-postgres-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-hermes-prod
    kind: ClusterSecretStore
  target:
    name: auth-postgres-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: hermes/prod/services/auth-db/postgres
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: hermes/prod/services/auth-db/postgres
        property: POSTGRES_PASSWORD
    - secretKey: APP_USER
      remoteRef:
        key: hermes/prod/services/auth-db/postgres
        property: APP_USER
    - secretKey: APP_PASSWORD
      remoteRef:
        key: hermes/prod/services/auth-db/postgres
        property: APP_PASSWORD
    - secretKey: FLYWAY_USER
      remoteRef:
        key: hermes/prod/services/auth-db/postgres
        property: FLYWAY_USER
    - secretKey: FLYWAY_PASSWORD
      remoteRef:
        key: hermes/prod/services/auth-db/postgres
        property: FLYWAY_PASSWORD
