apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
__EXTRA_RESOURCES__
configMapGenerator:
- name: __SERVICE_NAME__-config
  envs:
  - params.env
labels:
- pairs:
    environment: __ENVIRONMENT__
  includeSelectors: true
