apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../../../shared/postgres/auth-db/overlays/dev-local
- ../../../../shared/redis/auth-redis/overlays/dev
configMapGenerator:
- name: auth-service-config
  envs:
  - ../dev/params.env
secretGenerator:
- name: auth-service-secrets
  envs:
  - ../dev/secrets.env
labels:
- pairs:
    environment: dev
    secret-source: local
  includeSelectors: true
