apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
configMapGenerator:
- name: ws-gateway-config
  envs:
  - ../dev/params.env
secretGenerator:
- name: ws-gateway-secrets
  literals:
  - _PLACEHOLDER=unused
labels:
- pairs:
    environment: dev
    secret-source: local
  includeSelectors: true
