apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../../../shared/redis/gateway-cache/overlays/dev
configMapGenerator:
- name: gateway-config
  envs:
  - params.env
labels:
- pairs:
    environment: dev
  includeSelectors: true
