apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: __PG_SECRETS__
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: __SECRET_STORE__
    kind: ClusterSecretStore
  target:
    name: __PG_SECRETS__
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: __VAULT_PATH__
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: __VAULT_PATH__
        property: POSTGRES_PASSWORD
    - secretKey: APP_USER
      remoteRef:
        key: __VAULT_PATH__
        property: APP_USER
    - secretKey: APP_PASSWORD
      remoteRef:
        key: __VAULT_PATH__
        property: APP_PASSWORD
    - secretKey: FLYWAY_USER
      remoteRef:
        key: __VAULT_PATH__
        property: FLYWAY_USER
    - secretKey: FLYWAY_PASSWORD
      remoteRef:
        key: __VAULT_PATH__
        property: FLYWAY_PASSWORD
