apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: __SERVICE_NAME__-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: __SECRET_STORE__
    kind: ClusterSecretStore
  target:
    name: __SERVICE_NAME__-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_USER
      remoteRef:
        key: __VAULT_PATH__
        property: APP_USER
    - secretKey: APP_PASSWORD
      remoteRef:
        key: __VAULT_PATH__
        property: APP_PASSWORD
    - secretKey: FLYWAY_USER
      remoteRef:
        key: __VAULT_PATH__
        property: FLYWAY_USER
    - secretKey: FLYWAY_PASSWORD
      remoteRef:
        key: __VAULT_PATH__
        property: FLYWAY_PASSWORD
    - secretKey: RABBITMQ_USERNAME
      remoteRef:
        key: hermes/__VAULT_ENV__/shared/rabbitmq
        property: username
    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: hermes/__VAULT_ENV__/shared/rabbitmq
        property: password
